[package]
name = "concumining"
version = "0.1.0"
authors = ["luciana <lucianasl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33.0"
rand = "0.3.14"